### PR TITLE
fixing replacement of auth key in deepsearchconfig, closes issue #36

### PR DESCRIPTION
**Pull request by agiova**
Signed-off-by: agiova <giovannini.andrea@outlook.com>

### CODE REVIEW

**Comment by agiova** [comment]
Checks are failing, but is related to the preparation steps in github actions rather than the code to be checked.

Comparing with the last successfully checked commit of main:
- poetry version changed from 1.1.15 to 1.2.1
- runner image changed from version 20220821.1 to 20221002.2

**Comment by dolfim-ibm** [comment]
Thanks @agiova, the error you see resonates with other issues we found with poetry. Let me have a quick run and update a few dependencies.

**Comment by dolfim-ibm** [comment]
@agiova we fixes it now in `main`. We could rebase this (and maybe cleanup the broken attempts)

**Review by dolfim-ibm — APPROVED** [review]
Many thanks!

**Pull request merged**
